name: "Build multiarch images"
on: [workflow_dispatch]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4.1.0
      - name: Build image for ${{ matrix.os }}
        run: |
          docker build --tag myimage:${{ matrix.os }} .
          docker images
          docker run -i myimage:${{ matrix.os }} uname -a
          docker manifest inspect myimage:${{ matrix.os }}
      
